//  布局结构图片映射
export const layoutImgMap = {
	// logicalStructure: new URL("@/assets/img/logicalStructure.png", import.meta.url.href,
	logicalStructure: "/canvas/img/logicalStructure.png",
	mindMap: "/canvas/img/mindMap.png",
	organizationStructure: "/canvas/img/organizationStructure.png",
	catalogOrganization: "/canvas/img/catalogOrganization.png",
	timeline: "/canvas/img/timeline.png",
	timeline2: "/canvas/img/timeline2.png",
	fishbone: "/canvas/img/fishbone.png",
	verticalTimeline: "/canvas/img/verticalTimeline.png"
};

//  主题图片映射
export const themeMap = {
	default: "/canvas/img/default.jpg",
	classic: "/canvas/img/classic.jpg",
	minions: "/canvas/img/minions.jpg",
	pinkGrape: "/canvas/img/pinkGrape.jpg",
	mint: "/canvas/img/mint.jpg",
	gold: "/canvas/img/gold.jpg",
	vitalityOrange: "/canvas/img/vitalityOrange.jpg",
	greenLeaf: "/canvas/img/greenLeaf.jpg",
	dark2: "/canvas/img/dark2.jpg",
	skyGreen: "/canvas/img/skyGreen.jpg",
	classic2: "/canvas/img/classic2.jpg",
	classic3: "/canvas/img/classic3.jpg",
	classic4: "/canvas/img/classic4.jpg",
	classicGreen: "/canvas/img/classicGreen.jpg",
	classicBlue: "/canvas/img/classicBlue.jpg",
	blueSky: "/canvas/img/blueSky.jpg",
	brainImpairedPink: "/canvas/img/brainImpairedPink.jpg",
	dark: "/canvas/img/dark.jpg",
	earthYellow: "/canvas/img/earthYellow.jpg",
	freshGreen: "/canvas/img/freshGreen.jpg",
	freshRed: "/canvas/img/freshRed.jpg",
	romanticPurple: "/canvas/img/romanticPurple.jpg",
	simpleBlack: "/canvas/img/simpleBlack.jpg",
	courseGreen: "/canvas/img/courseGreen.jpg",
	coffee: "/canvas/img/coffee.jpg",
	redSpirit: "/canvas/img/redSpirit.jpg",
	blackHumour: "/canvas/img/blackHumour.jpg",
	lateNightOffice: "/canvas/img/lateNightOffice.jpg",
	blackGold: "/canvas/img/blackGold.jpg",
	autumn: "/canvas/img/autumn.jpg",
	avocado: "/canvas/img/avocado.jpg",
	orangeJuice: "/canvas/img/orangeJuice.jpg",
	oreo: "/canvas/img/oreo.jpg",
	shallowSea: "/canvas/img/shallowSea.jpg",
	lemonBubbles: "/canvas/img/lemonBubbles.jpg",
	rose: "/canvas/img/rose.jpg",
	seaBlueLine: "/canvas/img/seaBlueLine.jpg",
	neonLamp: "/canvas/img/neonLamp.jpg",
	darkNightLceBlade: "/canvas/img/darkNightLceBlade.jpg",
	morandi: "/canvas/img/morandi.jpg"
};
